### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by NiteshBharadwaj** [hrhodin/UnsupervisedGeometryAwareRepresentationLearning#2]
Can you share the background images? Is it one background per video or per image or per view-point?

**Comment by NiteshBharadwaj** [comment]
I am able to reproduce the results. Great codebase. Thank you.
Backgrounds: One background for each view followed by cropping using bounding boxes.

**Comment by hrhodin** [comment]
Correct.

**Comment by vru2020** [comment]
Hi @NiteshBharadwaj, do you have the processing script from background extraction ? Thanks a lot
