### ISSUE TITLE
Some question about label

### ISSUE THREAD

**Issue by zhyjiang** [hrhodin/UnsupervisedGeometryAwareRepresentationLearning#4]
Hi. We want to train our model using our dataset. However, we are confused about your label format. How do you build your global coordinate system? Is the rotation matrix from global coordinate or camera coordinate?

**Comment by hrhodin** [comment]
All camera matrices need to be in the same (global) coordinate system. It could be world coordinates or that of the first camera. Relative rotations between cameras are constructed by chaining the respective ones together.
