### ISSUE TITLE
3D pose coordinate system

### ISSUE THREAD

**Issue by matteorr** [hrhodin/UnsupervisedGeometryAwareRepresentationLearning#6]
Hi Helge,

I'm hoping to compare my results to the ones you report in Fig. 4(a). In that regard, I was hoping you could please clarify the following questions:

1. What is the coordinate system of the predicted 3d poses? In particular, given an input image from camera Ri is the network predicting the 3d pose in that reference system or is it predicting in the world reference system?

2. When you're training the [fully connected layers](https://github.com/hrhodin/UnsupervisedGeometryAwareRepresentationLearning/blob/master/python/models/MLP.py), are you freezing the weights of the encoder or are you also fine-tuning that at the same time?

Thanks a lot!

**Comment by hrhodin** [comment]
Hi,

1) Encodings and pose estimates are always relative to the camera.
2) All other weights are fixed. Otherwise, they would overfit to the few labeled examples.

-- Helge
