### ISSUE TITLE
Questions about rotation matrix and decoder implementation

### ISSUE THREAD

**Issue by mattiagaggi** [hrhodin/UnsupervisedGeometryAwareRepresentationLearning#7]
Hi Helge,

Thank you for the great paper and code you have made available, I have decided to reproduce it as part of my Masters project by writing my own code. 
I was wondering if you could help me out with a couple of issues I am having, the first one regarding the rotation matrix and the second one regarding the structure of the decoder.
Please could you review the below logic to see if it is consistent with your implementation?

1) given view points i and j,  the rotation from viewpoint i to j (cam2cam in the code) is found as follows:

- Get the rotation matrices world to camera R_w_to_i and R_w_to_j provided in the original dataset.

- Perform further rotations (call them R_i_to_root and R_j_to_root) on these such that the z axis of the camera coordinates is pointing at the root joint (which is also the center of the cropped image). This means that for viewpoint i if we apply the following transformations to the joints in world coordinates:    
translation_w_to_i from the original dataset -> R_w_to_i -> R_i_to_root , 
the z axis of the new coordinate system will point at the root.
 
- get R_i_j = R_j_to_root * R_w_to_j * (R_i_to_root * R_w_to_i)^(-1)    
(* stands for matrix multiplication obviously).
This corresponds to the step
cam2cam = torch.bmm(world_2_cam_suffled, cam_2_world) in the code.
Is this the correct procedure to get cam2cam?

2) As written in the paper the input to the decoder should have image dimensions 16 by 16 for an original image of 128 by 128 (end of page 9).
If we perform four convolutional blocks preceded by 1 bilinear interpolation and 3 up-convolutions (start of page 10) we will upsample by
2^4 so end up with image dimensions 256 by 256.
Is it just a typo or am I missing something?

Thank you!

Mattia

**Comment by hrhodin** [comment]
1. Looks good to me.
2. Thanks for the observation. We missed to update the implementation details in the paper text. It is three blocks with up-convolutions, followed by a single convolutional layer. No bilinear interpolation layers are used.

**Comment by mattiagaggi** [comment]
Hi,

great, thanks a lot, I appreciate the quick response.

Mattia
