### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by lvandoit** [hrhodin/UnsupervisedGeometryAwareRepresentationLearning#8]
while running the file of test_encodeDecode.py ,the following problems ouccurs.
ConnectionResetError: [Errno 104] Connection reset by peer.so what can i    @hrhodin

**Comment by hrhodin** [comment]
Do you run it on a remote server, do you have an X windows connection?
Please post the full output, but I don't think that it is specific to this codebase but your setup.

**Comment by lvandoit** [comment]
Thank you for your reply. I have successfully solved the current problem. Also thank you for your work，It means a lot to me

**Comment by hrhodin** [comment]
Can you explain what the problem was, such that others can avoid it?
